services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: keycloak
    environment:
      # konto administratora
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      # montujemy plik z realm-em dla importu
      - ./app-realm.json:/opt/keycloak/data/import/app-realm.json:ro
    # Quarkusowy start w trybie deweloperskim + import realm
    command: ["start-dev", "--import-realm"]
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT}"
    networks:
      - network_1

  frontend:
    build:
      context: ./frontend/.
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "${CLIENT_PORT}:80"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - KEYCLOAK_PORT=${KEYCLOAK_PORT}
      - CLIENT_PORT=${CLIENT_PORT}
    networks:
      - network_1
    depends_on:
      - keycloak
      - backend

  redis:
    image: redis:8-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    networks:
      - network_1

  backend:
    build: ./backend/.
    command: node Server.js
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - PORT=${BACKEND_PORT}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - network_1
    depends_on:
      - redis
    

# Definicja named volume
volumes:
  redis_data:

networks:
  network_1:
    driver: bridge
