apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: BACKEND_PORT
              value: "5000"
            - name: CLIENT_PORT
              value: "9000"
            - name: KEYCLOAK_PORT
              value: "8080"
          image: arek2904/frontend:1.0.0
          imagePullPolicy: IfNotPresent
          name: react-app
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
